name: publish
on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3.4.0
      - name: Get branch name
        uses: tj-actions/branch-names@v6.5
        id: extract_branch
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk 17
        uses: actions/setup-java@v3.10.0
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-${{ steps.extract_branch.outputs.current_branch }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Retrieve Version #https://stackoverflow.com/questions/71089787/how-to-get-version-name-from-android-gradle-file-in-github-actions
        run: |
          echo "VERSION_INFORMATION=$(${{github.workspace}}/gradlew -q printVersionName)" >> $GITHUB_ENV
          echo "VERSION_PLAIN=$(${{github.workspace}}/gradlew -q printVersion)" >> $GITHUB_ENV
      - name: build
        run: ./gradlew build
      - name: Publish Minecraft Mods
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          version-type: beta
          changelog-file: CHANGELOG.md
          name: ${{ env.VERSION_INFORMATION }}
          version: ${{ env.VERSION_PLAIN }}

          game-versions: |
            1.19.2

          loaders: |
            fabric

          java: |
            17

          modrinth-id: fLAsXzkA
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-featured: true
          modrinth-unfeature-mode: subset
          modrinth-dependencies: |
            fabric-api | depends | *

          curseforge-id: 825157
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          curseforge-dependencies: |
            fabric-api | depends | *